### ISSUE TITLE
Get keyword ideas

### ISSUE THREAD

**Issue by karakanb** [adprolabs/easy-adwords#1]
There should be a method for the keyword entity that performs a request to get keyword ideas with the given predicates. The package supports mutating multiple keywords in a group, however it does not get the keyword ideas, which was the main idea in mind while implementing the multiple keyword operation. Link [here](https://developers.google.com/adwords/api/docs/samples/php/optimization#get-keyword-ideas) may be useful.

**Comment by basperheim** [comment]
There hasn't been a commit to this repo in years, and the Google API library that this library was based on is now depreciated.

**Comment by karakanb** [comment]
Unfortunately, I am not able to work on this project anymore, and I don't think anybody has any plans to maintain it as well.
